import './globals.css'
import Footer from '@/components/footer'
import { GlobalContextProvider } from './Context'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
          { children }
        </GlobalContextProvider>
        <Footer></Footer>
      </body>
    </html>
  )
}
